### ISSUE TITLE
Pods-TetherMac.xcconfig

### ISSUE THREAD

**Issue by samsrose** [chrisballinger/Tether-iOS#4]
The file "Pods-Tether.xcconfig" couldn't be opened because there is no such file. (~/Documents/Tether-iOS/Pods/Pods-Tether.xcconfig)

After taking a look at the .gitignore (in both the TetherMac and Tether files), on line 11 you have "Pods/" commented out. It would be much appreciated if you could include this directory and its contents in the master branch. This would help prevent build failures, which are currently happening.

Thank you.

**Comment by chrisballinger** [comment]
Install CocoaPods and then run `pod install`

**Comment by mozeryansky** [comment]
@chrisballinger Can you add that to the README?
